name    'metcalfc-rpmrepos'
version '0.0.1'
source 'http://github.com/metcalfc/puppet-rpmrepos'
author 'metcalfc'
license 'Apache License, Version 2.0'
summary 'Setup 3rd party RPM repos'
description 'Setup the various third party repos on Centos/RHEL et all'
project_page 'http://github.com/metcalfc/puppet-rpmrepos'
